### ISSUE TITLE
No se comprueba si el año es bisiesto

### ISSUE THREAD

**Issue by RafaSojo** [Ramirez9/Ramirez9.github.io#11]
https://github.com/Ramirez9/Ramirez9.github.io/blob/7e74b14def7ca2167a0f8196a87096931782fa7a/cliente/Tema-3/exCreadoNoviembreFranciscoRamirez/js/info.js#L90

Cuando se calcula la fecha no se tiene en cuenta los años bisiestos por lo que la fecha está mal.

**Comment by Ramirez9** [comment]
No era la didáctica del ejercicio, el examinado no tenía que comprobarlo.
